### ISSUE TITLE
Add credit for gif background

### ISSUE THREAD

**Issue by machikoyasuda** [elrandomhero/hello#3]

**Comment by machikoyasuda** [comment]
The artist is https://twitter.com/Kirokaze http://kirokaze.deviantart.com/ Gerardo Quiroz V. 

Maybe @elrandomhero we should add a link and emoji to his site on your site :)

**Comment by elrandomhero** [comment]
@machikoyasuda yes!

**Comment by machikoyasuda** [comment]
if you wanna pair program on this tonight in downtown: http://www.meetup.com/la-fullstack/events/233276393/ come! :) 

241 S Figueroa St.
Suite 240
Los Angeles, CA 90012
